name: WebdriverIO Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
